vegtables = {
    "o": "Onion",
    "p": "Potato",
    "t": "Tomato",
    "c": "Carrot",
    "b": "Brinjal",
    "ca": "Capsicum",
    "l": "Lemon",
    "ga": "Garlic",
    "gi": "Ginger",
    "cb": "Cabbage",
    "cf": "Cauliflower",
    "cu": "Cucumber",
    "bp": "Bitter Gourd",
    "ok": "Ladyfinger",
    "bg": "Bottle Gourd",
    "ds": "Drumstick",
    "ch": "Green Chili",
    "pe": "Peas",
    "sp": "Spinach",
    "mt": "Methi",
    "ko": "Kohlrabi",
    "ra": "Radish",
    "be": "Beetroot",
    "tu": "Turnip",
    "pa": "Parwal",
    "pg": "Pointed Gourd",
    "sn": "Snake Gourd",
    "rg": "Ridge Gourd",
    "mg": "Mushroom",
    "sc": "Spring Onion",
    "le": "Leek",
    "ze": "Zucchini",
    "as": "Asparagus",
    "ar": "Arbi",
    "ya": "Yam",
    "su": "Sweet Potato",
    "ba": "Banana Flower",
    "bl": "Bottle Gourd Leaves",
    "am": "Amaranth",
    "fe": "Fenugreek Leaves",
    "co": "Coriander",
    "mi": "Mint",
    "cu": "Curry Leaves",
    "ka": "Kale",
    "ch": "Chard",
    "br": "Broccoli",
    "ca": "Celery",
    "av": "Avocado",
    "to": "Taro",
    "ed": "Edamame",
    "wa": "Water Chestnut",
    "ba": "Bamboo Shoot",
    "so": "Sorrel",
    "mu": "Mustard Greens"
}

price = {
    "Sasha": 0.025,
    "Gajor": 0.03019,
    "Onion": 0.080,
    "Potato": 0.050,
    "Tomato": 0.120,
    "Carrot": 0.060,
    "Brinjal": 0.045,
    "Capsicum": 0.060,
    "Lemon": 0.114,
    "Garlic": 0.220,
    "Ginger": 0.200,
    "Cabbage": 0.050,
    "Cauliflower": 0.070,
    "Cucumber": 0.050,
    "Bitter Gourd": 0.080,
    "Ladyfinger": 0.100,
    "Bottle Gourd": 0.060,
    "Drumstick": 0.060,
    "Green Chili": 0.060,
    "Peas": 0.220,
    "Spinach": 0.040,
    "Methi": 0.050,
    "Kohlrabi": 0.045,
    "Radish": 0.040,
    "Beetroot": 0.050,
    "Turnip": 0.045,
    "Parwal": 0.060,
    "Pointed Gourd": 0.060,
    "Snake Gourd": 0.050,
    "Ridge Gourd": 0.050,
    "Mushroom": 0.085,
    "Spring Onion": 0.050,
    "Leek": 0.070,
    "Zucchini": 0.080,
    "Asparagus": 0.150,
    "Arbi": 0.060,
    "Yam": 0.050,
    "Sweet Potato": 0.055,
    "Banana Flower": 0.040,
    "Bottle Gourd Leaves": 0.030,
    "Amaranth": 0.035,
    "Fenugreek Leaves": 0.040,
    "Coriander": 0.050,
    "Mint": 0.060,
    "Curry Leaves": 0.050,
    "Kale": 0.080,
    "Chard": 0.070,
    "Broccoli": 0.120,
    "Celery": 0.060,
    "Avocado": 0.150,
    "Taro": 0.050,
    "Edamame": 0.100,
    "Water Chestnut": 0.080,
    "Bamboo Shoot": 0.090,
    "Sorrel": 0.040,
    "Mustard Greens": 0.045
}